os: Visual Studio 2015

platform: x64

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/tadzik/rakudobrew %USERPROFILE%\rakudobrew
  - SET PATH=%USERPROFILE%\rakudobrew\bin;%PATH%
  - rakudobrew build moar
  - rakudobrew build panda
  - cd %APPVEYOR_BUILD_FOLDER%
  - panda --notests installdeps .
  - perl6 -MPanda::Builder -e 'Panda::Builder.build(~$*CWD)'

build: false

test_script:
  - prove -v -e "perl6 -Ilib" t/

shallow_clone: true

notifications:

  # Email
  - provider: Email
    to:
      - samgwise@gmail.com
    subject: 'Numeric::Pack build {{status}}'           # optional
    message: "{{message}}, {{commitId}}, {{status}}"    # optional
    on_build_status_changed: true
